import { formatISO } from "date-fns";
import type { GrowthSnapshot } from "@/lib/types";

export const getDemoSnapshot = (): GrowthSnapshot => ({
  generatedAt: formatISO(new Date()),
  kpis: [
    { label: "GMV（成交额）", value: "$184,260", delta: "近 7 天 +18.4%", tone: "good" },
    { label: "真实 ROAS（广告回报）", value: "3.42x", delta: "同步利润后 +0.31", tone: "good" },
    { label: "CPA（获客成本）", value: "$28.60", delta: "US（美国）/ CA（加拿大）-12.1%", tone: "good" },
    { label: "待人工确认", value: "9", delta: "3 个高影响动作", tone: "warn" },
  ],
  countryMetrics: [
    { country: "US", spendCents: 426000, revenueCents: 1689000, grossProfitCents: 612000, cpaCents: 2860, roasBps: 39600 },
    { country: "CA", spendCents: 138000, revenueCents: 496000, grossProfitCents: 174000, cpaCents: 2460, roasBps: 35900 },
    { country: "UK", spendCents: 210000, revenueCents: 642000, grossProfitCents: 214000, cpaCents: 3180, roasBps: 30600 },
    { country: "AU", spendCents: 126000, revenueCents: 354000, grossProfitCents: 107000, cpaCents: 3320, roasBps: 28100 },
    { country: "DE", spendCents: 104000, revenueCents: 244000, grossProfitCents: 62000, cpaCents: 4120, roasBps: 23500 },
    { country: "FR", spendCents: 97000, revenueCents: 212000, grossProfitCents: 51000, cpaCents: 4380, roasBps: 21900 },
  ],
  integrations: [
    { id: "shopify", provider: "shopify", name: "Shopify / 独立站", status: "demo", accountRef: null, lastSyncAt: null, hint: "接入店铺、商品、订单与客户基础数据，优先用于独立站业务验证。", inputLabel: "店铺域名" },
    { id: "meta", provider: "meta_ads", name: "Meta Ads（Meta 广告）", status: "demo", accountRef: null, lastSyncAt: null, hint: "同步广告账户、花费、转化与素材表现，用于投流驾驶舱分析。", inputLabel: "广告账户 ID" },
    { id: "tiktok", provider: "tiktok_ads", name: "TikTok Ads（TikTok 广告）", status: "demo", accountRef: null, lastSyncAt: null, hint: "接入 TikTok 广告数据，监控短视频投流成本、转化与素材效率。", inputLabel: "Advertiser ID（广告主 ID）" },
    { id: "instagram", provider: "instagram_graph", name: "Instagram Graph（Instagram 数据接口）", status: "demo", accountRef: null, lastSyncAt: null, hint: "接入 Instagram 商业账号内容、互动与潜在客户线索数据。", inputLabel: "Business Account ID（商业账号 ID）" },
    { id: "logistics", provider: "logistics", name: "物流 API（物流接口）", status: "demo", accountRef: null, lastSyncAt: null, hint: "同步发货状态、轨迹节点、异常包裹与售后查询所需物流信息。", inputLabel: "物流账号 / API Profile（接口配置）" },
    { id: "support", provider: "support", name: "客服系统", status: "demo", accountRef: null, lastSyncAt: null, hint: "接入独立站客服、邮件客服或第三方客服工作区，汇入统一客服台。", inputLabel: "客服工作区" },
  ],
  supportCustomers: [
    { id: "cus_1", displayName: "Emily Carter", primaryEmail: "emily@example.com", primaryPhone: null, country: "US", language: "en-US" },
    { id: "cus_2", displayName: "李先生", primaryEmail: "li@example.cn", primaryPhone: "+86 138****0000", country: "OTHER", language: "zh-CN" },
    { id: "cus_3", displayName: "Sophie Martin", primaryEmail: "sophie@example.fr", primaryPhone: null, country: "FR", language: "fr-FR" },
  ],
  customerIdentities: [
    { id: "cid_1", customerId: "cus_1", channel: "independent_site_chat", externalUserId: "site_chat_88421", displayName: "Emily C." },
    { id: "cid_2", customerId: "cus_2", channel: "email", externalUserId: "li@example.cn", displayName: "李先生" },
    { id: "cid_3", customerId: "cus_3", channel: "independent_site_form", externalUserId: "form_20260602_19", displayName: "Sophie Martin" },
  ],
  supportThreads: [
    {
      id: "th_1",
      customerId: "cus_1",
      channel: "independent_site_chat",
      subject: "客户询问订单发货时间",
      status: "ai_managed",
      riskLevel: "medium",
      language: "en-US",
      orderRef: "AS-1041",
      lastMessageAt: formatISO(new Date()),
    },
    {
      id: "th_2",
      customerId: "cus_2",
      channel: "email",
      subject: "客户要求退款",
      status: "needs_human",
      riskLevel: "high",
      language: "zh-CN",
      orderRef: "AS-1028",
      lastMessageAt: formatISO(new Date()),
    },
    {
      id: "th_3",
      customerId: "cus_3",
      channel: "independent_site_form",
      subject: "潜在客户咨询刻字款式",
      status: "open",
      riskLevel: "low",
      language: "fr-FR",
      orderRef: null,
      lastMessageAt: formatISO(new Date()),
    },
  ],
  supportMessages: [
    {
      id: "msg_1",
      threadId: "th_1",
      channel: "independent_site_chat",
      direction: "inbound",
      senderType: "customer",
      senderRef: "site_chat_88421",
      originalText: "Hi, when will my order AS-1041 be delivered?",
      createdAt: formatISO(new Date()),
    },
    {
      id: "msg_2",
      threadId: "th_2",
      channel: "email",
      direction: "inbound",
      senderType: "customer",
      senderRef: "li@example.cn",
      originalText: "我要退款，订单 AS-1028 的刻字好像不对。",
      createdAt: formatISO(new Date()),
    },
    {
      id: "msg_3",
      threadId: "th_3",
      channel: "independent_site_form",
      direction: "inbound",
      senderType: "customer",
      senderRef: "form_20260602_19",
      originalText: "Bonjour, est-ce que vous pouvez graver deux initiales sur la montre ?",
      createdAt: formatISO(new Date()),
    },
  ],
  messageTranslations: [
    {
      id: "tr_1",
      messageId: "msg_1",
      sourceLanguage: "en-US",
      targetLanguage: "zh-CN",
      translatedText: "您好，我的 AS-1041 订单什么时候送达？",
      modelName: "demo-translation",
      humanEdited: false,
    },
    {
      id: "tr_2",
      messageId: "msg_3",
      sourceLanguage: "fr-FR",
      targetLanguage: "zh-CN",
      translatedText: "您好，这款手表可以刻两个姓名首字母吗？",
      modelName: "demo-translation",
      humanEdited: false,
    },
  ],
  aiReplySuggestions: [
    {
      id: "ars_1",
      threadId: "th_1",
      messageId: "msg_1",
      draftText: "Hi, thanks for your message. We have received your order number AS-1041. Our support team will check the latest logistics status and follow up when online.",
      riskLevel: "medium",
      reason: "客户询问物流，AI 可收集订单号并引导等待人工确认，不承诺具体送达时间。",
      status: "pending_review",
      canAutoSend: false,
      createdAt: formatISO(new Date()),
    },
    {
      id: "ars_2",
      threadId: "th_2",
      messageId: "msg_2",
      draftText: "您好，已收到您的退款诉求。我们会先记录订单号和问题原因，客服上班后核实订单与刻字信息后继续处理。",
      riskLevel: "high",
      reason: "退款和定制争议属于高风险售后，AI 不允许承诺退款或补偿。",
      status: "pending_review",
      canAutoSend: false,
      createdAt: formatISO(new Date()),
    },
    {
      id: "ars_3",
      threadId: "th_3",
      messageId: "msg_3",
      draftText: "Bonjour, oui, nous pouvons généralement graver deux initiales. Vous pouvez envoyer les initiales souhaitées, et notre équipe confirmera les détails avant la production.",
      riskLevel: "low",
      reason: "基础产品咨询，AI 可低风险引导客户提供刻字信息。",
      status: "pending_review",
      canAutoSend: true,
      createdAt: formatISO(new Date()),
    },
  ],
  aiApprovals: [
    {
      id: "apv_1",
      sourceType: "ai_reply_suggestion",
      sourceId: "ars_3",
      riskLevel: "low",
      decision: "approved",
      approverRef: "support_demo_user",
      finalText: "Bonjour, oui, nous pouvons graver deux initiales. Merci de nous envoyer les initiales souhaitées.",
      humanEdited: true,
      decidedAt: formatISO(new Date()),
    },
  ],
  handoffReports: [
    {
      id: "hr_1",
      reportDate: "2026-06-02",
      windowStart: "2026-06-01T18:00:00+08:00",
      windowEnd: "2026-06-02T09:00:00+08:00",
      newThreadsCount: 3,
      aiRepliesCount: 1,
      needsHumanCount: 2,
      highRiskCount: 1,
      priorityThreads: ["th_2", "th_1"],
      summary: "昨晚托管期间新增 3 条会话，1 条退款争议必须人工优先处理，1 条物流咨询需客服确认物流状态。",
    },
  ],
  creators: [
    { id: "cr_1", platform: "TikTok", handle: "@watchwithmia", country: "US", followers: 184000, avgViews: 52000, engagementRateBps: 684, aiScore: 92, status: "sample_sent", tags: ["gift guide（礼物指南）", "couple（情侣）", "custom watch（定制腕表）"] },
    { id: "cr_2", platform: "Instagram", handle: "@londonfits", country: "UK", followers: 96000, avgViews: 31000, engagementRateBps: 512, aiScore: 86, status: "discovered", tags: ["men style（男士穿搭）", "minimal（极简风）", "UGC（用户原创内容）"] },
    { id: "cr_3", platform: "TikTok", handle: "@timeless.au", country: "AU", followers: 142000, avgViews: 47000, engagementRateBps: 604, aiScore: 81, status: "authorized", tags: ["unboxing（开箱）", "wrist shot（上手镜头）", "holiday（节日礼物）"] },
  ],
  creatives: [
    { id: "cv_1", title: "3 秒刻字特写开头（3s engraving hook）", source: "creator", platform: "TikTok", country: "US", hookScore: 94, completionScore: 86, clickScore: 82, scaleScore: 91, status: "scaling" },
    { id: "cv_2", title: "情侣纪念日开箱（His & hers reveal）", source: "organic", platform: "Instagram", country: "UK", hookScore: 88, completionScore: 79, clickScore: 85, scaleScore: 84, status: "testing" },
    { id: "cv_3", title: "工厂定制流程（Factory customization）", source: "organic", platform: "TikTok", country: "DE", hookScore: 66, completionScore: 72, clickScore: 58, scaleScore: 61, status: "paused" },
    { id: "cv_4", title: "百美元内轻奢礼物（Luxury gift under $100）", source: "ad", platform: "Meta", country: "GLOBAL", hookScore: 90, completionScore: 83, clickScore: 89, scaleScore: 93, status: "scaling" },
  ],
  adMetrics: [
    { id: "ad_1", creative: "百美元内轻奢礼物（Luxury gift under $100）", country: "US", audience: "礼物买家相似人群（Gift buyers LAL 2%）", spendCents: 182000, revenueCents: 768000, grossProfitCents: 284000, impressions: 182000, clicks: 6420, orders: 70, cpaCents: 2590, roasBps: 42200, recommendation: "预算 +20%，需确认" },
    { id: "ad_2", creative: "3 秒刻字特写开头（3s engraving hook）", country: "CA", audience: "情侣礼物兴趣人群（Couple gift interests）", spendCents: 62000, revenueCents: 248000, grossProfitCents: 91000, impressions: 59000, clicks: 2240, orders: 28, cpaCents: 2210, roasBps: 40000, recommendation: "复制到 US（美国）相似人群" },
    { id: "ad_3", creative: "工厂定制流程（Factory customization）", country: "DE", audience: "广泛人群 25-44（Broad 25-44）", spendCents: 54000, revenueCents: 96000, grossProfitCents: 22000, impressions: 51000, clicks: 1020, orders: 11, cpaCents: 4870, roasBps: 17800, recommendation: "暂停并重剪前 3 秒" },
  ],
  orders: [
    { id: "or_1", externalOrderId: "AS-1028", country: "US", channel: "Meta Ads（Meta 广告）", revenueCents: 12900, customization: { engraving: "A+M 2026", color: "Gold（金色）", size: "42mm" }, fulfillmentStatus: "custom_confirm", riskFlags: ["engraving_confirm"] },
    { id: "or_2", externalOrderId: "AS-1034", country: "CA", channel: "TikTok Creator（TikTok 达人）", revenueCents: 9900, customization: { color: "Rose Gold（玫瑰金）", imageRequired: true }, fulfillmentStatus: "production", riskFlags: [] },
    { id: "or_3", externalOrderId: "AS-1041", country: "UK", channel: "Organic TikTok（TikTok 自然流量）", revenueCents: 14900, customization: { engraving: "Forever", color: "Black（黑色）", size: "40mm" }, fulfillmentStatus: "shipped", riskFlags: ["carrier_delay"] },
  ],
  aiActions: [
    { id: "act_1", ownerRole: "gm", actionType: "budget_change", title: "Meta US（美国）广告活动预算 +20%", detail: "基于真实毛利 ROAS（广告回报）4.22x，但会增加日消耗 $360，需要人工确认。", riskLevel: "high", status: "pending", createdAt: formatISO(new Date()) },
    { id: "act_2", ownerRole: "bd", actionType: "creator_message", title: "给 @londonfits 发送英文 DM（私信）", detail: "AI（人工智能）已生成个性化话术，发送前需确认品牌口吻和样品承诺。", riskLevel: "medium", status: "pending", createdAt: formatISO(new Date()) },
    { id: "act_3", ownerRole: "media_buyer", actionType: "creative_pause", title: "暂停 DE（德国）低效素材", detail: "CPA（获客成本）高于目标 38%，素材 3 秒吸引力低于 70 分。", riskLevel: "low", status: "pending", createdAt: formatISO(new Date()) },
    { id: "act_4", ownerRole: "support", actionType: "support_reply", title: "订单 AS-1028 定制信息确认", detail: "客户刻字字段疑似包含拼写错误，建议发确认邮件。", riskLevel: "medium", status: "pending", createdAt: formatISO(new Date()) },
  ],
});
